DOMAIN = "guntamagic"
CONF_IP_ADDRESS = "IP address of the entity (e.g. 192.168.1.10)"
CONF_KEY = "Your key for the log gasifier interface provided by guntamatic"
CONF_NAME = "Name of the entity (e.g. BMK20)"
CONF_MAPPING_FILE = "mapping_file"